<?xml version="1.0"?>
<robot name="jackal" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- This file is a placeholder which is included by default from
       jackal.urdf.xacro. If a robot is being customized and requires
       additional URDF, set the JACKAL_URDF_EXTRAS environment variable
       to the full path of the file you would like included. -->
  
  <xacro:property name="asm_l" value="0.532" />
  <xacro:property name="asm_w" value="0.416" />
  <xacro:property name="asm_h" value="0.308" />
  
  <xacro:property name="holder_l" value="0.05" />
  <xacro:property name="holder_w" value="0.028" />
  <xacro:property name="holder_h" value="0.04" />
  
   <joint name="chassis_frame_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="asm_link" />
      <axis xyz="0 0 1" />
   </joint>

  <link name="asm_link">
    <visual>
      <origin xyz="0.01 0.0 ${chassis_height}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://jackal_description/meshes/jackal_frame.stl"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
      <origin xyz="-0.03 0 ${asm_h/2+chassis_height}"/>
      <geometry>
        <box size="${asm_l-0.05} ${asm_w-0.05} ${asm_h-0.05}"/>
      </geometry>
    </collision>
    <inertial>
      <!-- Center of mass -->
      <origin xyz="0 0 ${asm_h/2}" rpy="0 0 0"/>
      <mass value="2.0"/>
      <!-- Moments of inertia: -->
      <inertia
        ixx="0.2" ixy="-0.0000" ixz="0.00"
        iyy="0.2" iyz="-0.0000" 
        izz="0.2"/>
      </inertial>
  </link>
  
  <joint name="frame_holder_joint" type="fixed">
      <parent link="asm_link"/>
      <child link="holder_link" />
      <axis xyz="0 0 1" />
   </joint>
    
  <link name="holder_link">
    <visual>
      <origin xyz="0.215 0.01 ${chassis_height+0.15}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://jackal_description/meshes/camera_holder.stl"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
      <origin xyz="0 0 ${holder_h/2}"/>
      <geometry>
        <box size="${holder_w} ${holder_l} ${holder_h}"/>
      </geometry>
    </collision>
    <inertial>
      <!-- Center of mass -->
      <origin xyz="0 0 ${holder_h/2}" rpy="0 0 0"/>
      <mass value="0.01"/>
      <!-- Moments of inertia: -->
      <inertia
        ixx="0.1" ixy="-0.0000" ixz="0.00"
        iyy="0.1" iyz="-0.0000" izz="0.1"/>
      </inertial>
  </link>
</robot>
